import PDFDocument from "pdfkit";

interface PdfOptions {
  title: string;
  businessName: string;
  date: string;
}

/**
 * Converts markdown content to a formatted PDF buffer.
 *
 * Handles H1/H2/H3 headings, paragraphs, bullet lists, numbered lists,
 * tables (basic), bold/italic, and source links.
 */
export async function generatePdf(content: string, options: PdfOptions): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margins: { top: 72, bottom: 72, left: 72, right: 72 },
      info: {
        Title: options.title,
        Author: options.businessName,
        Subject: "Generated by AIRS",
        Creator: "AIRS Content Generator",
      },
    });

    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;

    // Title page
    doc.fontSize(24).font("Helvetica-Bold").text(options.title, { align: "center", width: pageWidth });
    doc.moveDown(0.5);
    doc.fontSize(14).font("Helvetica").text(options.businessName, { align: "center", width: pageWidth });
    doc.moveDown(0.3);
    doc.fontSize(10).fillColor("#888888").text(`Generated: ${options.date}`, { align: "center", width: pageWidth });
    doc.fillColor("#000000");
    doc.moveDown(2);
    doc.fontSize(8).fillColor("#aaaaaa").text("Generated by AIRS Content Generator", { align: "center", width: pageWidth });
    doc.fillColor("#000000");

    doc.addPage();

    const lines = content.split("\n");
    let inTable = false;
    let tableHeaders: string[] = [];

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      const trimmed = line.trim();

      if (trimmed === "") {
        if (inTable) {
          inTable = false;
          tableHeaders = [];
        }
        doc.moveDown(0.3);
        continue;
      }

      if (trimmed.startsWith("# ") && !trimmed.startsWith("## ")) {
        doc.fontSize(18).font("Helvetica-Bold").text(trimmed.substring(2), { width: pageWidth });
        doc.moveDown(0.3);
        doc.font("Helvetica").fontSize(11);
      } else if (trimmed.startsWith("## ") && !trimmed.startsWith("### ")) {
        if (doc.y > doc.page.height - 120) doc.addPage();
        doc.moveDown(0.5);
        doc.fontSize(15).font("Helvetica-Bold").text(trimmed.substring(3), { width: pageWidth });
        doc.moveDown(0.2);
        doc.font("Helvetica").fontSize(11);
      } else if (trimmed.startsWith("### ")) {
        if (doc.y > doc.page.height - 100) doc.addPage();
        doc.moveDown(0.3);
        doc.fontSize(13).font("Helvetica-Bold").text(trimmed.substring(4), { width: pageWidth });
        doc.moveDown(0.1);
        doc.font("Helvetica").fontSize(11);
      } else if (trimmed.startsWith("| ") && trimmed.endsWith("|")) {
        const cells = trimmed.split("|").map((c) => c.trim()).filter(Boolean);
        if (cells.every((c) => /^[-:]+$/.test(c))) {
          continue;
        }
        if (!inTable) {
          inTable = true;
          tableHeaders = cells;
          doc.moveDown(0.2);
          doc.font("Helvetica-Bold").fontSize(10);
          const colWidth = pageWidth / cells.length;
          cells.forEach((cell, idx) => {
            doc.text(cell, doc.page.margins.left + idx * colWidth, doc.y, { width: colWidth - 5 });
          });
          doc.moveDown(0.1);
          doc.font("Helvetica").fontSize(10);
        } else {
          const colWidth = pageWidth / cells.length;
          const startY = doc.y;
          cells.forEach((cell, idx) => {
            doc.text(cell, doc.page.margins.left + idx * colWidth, startY, { width: colWidth - 5 });
          });
          doc.moveDown(0.1);
        }
      } else if (trimmed.startsWith("- ") || trimmed.startsWith("* ")) {
        doc.fontSize(11).font("Helvetica");
        const text = trimmed.substring(2);
        const bulletX = doc.page.margins.left + 10;
        doc.text("•", doc.page.margins.left, doc.y, { width: 15 });
        doc.text(text, bulletX, doc.y - 12, { width: pageWidth - 15 });
        doc.moveDown(0.1);
      } else if (/^\d+\.\s/.test(trimmed)) {
        doc.fontSize(11).font("Helvetica");
        const match = trimmed.match(/^(\d+)\.\s(.*)/);
        const num = match ? match[1] : "";
        const text = match ? match[2] : trimmed;
        doc.text(`${num}.`, doc.page.margins.left, doc.y, { width: 20 });
        doc.text(text, doc.page.margins.left + 20, doc.y - 12, { width: pageWidth - 20 });
        doc.moveDown(0.1);
      } else {
        if (doc.y > doc.page.height - 80) doc.addPage();
        doc.fontSize(11).font("Helvetica");

        let processedLine = trimmed;
        processedLine = processedLine.replace(/\*\*([^*]+)\*\*/g, "$1");
        processedLine = processedLine.replace(/\*([^*]+)\*/g, "$1");
        processedLine = processedLine.replace(/\[([^\]]+)\]\(([^)]+)\)/g, "$1 ($2)");

        doc.text(processedLine, { width: pageWidth, align: "left" });
        doc.moveDown(0.15);
      }
    }

    // Footer with page numbers
    const range = doc.bufferedPageRange();
    for (let i = 0; i < range.count; i++) {
      doc.switchToPage(i);
      const bottom = doc.page.height - 30;
      doc.fontSize(8).fillColor("#aaaaaa").text(
        `Page ${i + 1} of ${range.count} · AIRS`,
        doc.page.margins.left,
        bottom,
        { width: pageWidth, align: "center" }
      );
      doc.fillColor("#000000");
    }

    doc.end();
  });
}
